### ISSUE TITLE
Daily Health Check Up 19 Jan 2019

### ISSUE THREAD

**Issue by puneet-tm** [puneet-tm/wirelessone-support#1]
Daily Health Check Up 19 Jan 2019

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm please find below today's daily health check up report:

Hello Team,
There is no issue found on production.

[Production Health Report 19-1-2019.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2775310/Production.Health.Report.19-1-2019.xlsx)

**Comment by rohitgupta-tm** [comment]
@santoshkhairnar-tm @sohailshaikh-tm @rupalivaidya-tm @swapnildabhole-tm 
Hello Team,
Request you to please share your daily Heath check up.
Priority Points:
Discovery
KPI
Alert Center
Server Load(DB query/Process list)
Other important updates.
