### ISSUE TITLE
Swapnil and Rupali Training

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#10]
Hello Team,
Please let me know about the training for @rupalivaidya-tm @swapnildabhole-tm

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm 
Today's training topics of Swapnil:

1)Capacity Management
2)Weekly Report

**Comment by swapnildabhole-tm** [comment]
@rohitgupta-tm 

checked following reports today:
Sector Utilization TOT
BH Topology 
Customer VLAN
Radwin5k CRC Error
GSU CRC error

capacity Management

**Comment by swapnildabhole-tm** [comment]
Checked following report today:
Network Report
Customer Report
Performance Report

Completed following Module
Dashboard Except Sector spot,problem tickit, customer fault,Network performance etc.
Network Maps Except Points
Alert Center except TT management,PE event, LQI
Escalation
capacity management
Performance Report
Download Center except Discovery, GIS inventory, manual user report

@rohitgupta-tm

**Comment by puneet-tm** [comment]
@rohitgupta-tm Please share the review status for this week for Rupali and Swapnil.

**Comment by rohitgupta-tm** [comment]
Hello Sir,
Review Status for Swapnil and Rupal.
Review taken for 2 module(30 min) Dashboard and Network Map
Rupali = 7.5/10
Swapnil=3/10

Review is based on basic questions.

**Comment by swapnildabhole-tm** [comment]
Checked following report today:
Production Health report.
Server checklist
KPI services.
Download Reports

@rohitgupta-tm

**Comment by swapnildabhole-tm** [comment]
checked following report today
Production health report.
server checklist
Download report
kpi services.

**Comment by rohitgupta-tm** [comment]
Hello Rupali and Swapnil,
KT has been completed not Review session is started.
