### ISSUE TITLE
User identified: Cosmetic Changes RED/Green Event : RF NW Incident || INCC01031910492 || Base Station is Unreachable [NARAYANGAON, 10.139.236.10, PN-RoM-Goa] Cust Count : 11 - High Impact

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#100]
Please check as below.

1.	Email missing as below 
2.     Attachment missing
3.     Email Missing due to alert center issue - attached email

**Comment by rupalivaidya-tm** [comment]
Team is working on it.

**Comment by rupalivaidya-tm** [comment]
This is not an issue,this is changes which is deployed on 16 Feb

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm please close this case
