### ISSUE TITLE
User identified: W1 Discrepancy PUNJAN & Green Model Town BTS.

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#108]
Please check below 2 cases and get these fix the issues.
Case 1 : Duplicate BTS entry present for UBR BH BTS : Green Model Town
Case 2 : Getting 2 different BTS topo view as we are checking for PUNJAN BTS.

**Comment by santoshkhairnar-tm** [comment]
We have got 2 Different Site ID for same BS and one of the site id is invalid(in “/” format)

**Comment by rohitgupta-tm** [comment]
RCA:We have got 2 Different Site ID for same BS and one of the site id is invalid(in “/” format)
