### ISSUE TITLE
Daily Health Checkup 20th Jan 2019

### ISSUE THREAD

**Issue by sarveshreddy-tm** [puneet-tm/wirelessone-support#11]
Hello Team,
Please find Daily Health Checklist of 20-1-19.
Following issue found on Production,

1 | KPI Issue | KPI Not Running for both n/w and customer live | Subhash

2 | Discovery Sync issue | Today sync not run by discovery, yesterday sync status pending | Rupam

@rupalivaidya-tm @rohitgupta-tm @sohailshaikh-tm

**Comment by rohitgupta-tm** [comment]
Please update KPI issue in Airflow also
