### ISSUE TITLE
Monthly KPI Status Task(April)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#115]
KPI status For April month

**Comment by sarveshreddy-tm** [comment]
KPI Running Fine

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI Running Fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running Fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running Fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running Fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine
.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but getting double values.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine but observed double values for UL Issue service.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine but observed double value for UL issue service at 7:47am

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine but ul issue not working from 15:12.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine and ul issue also working from 19:52

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL kpi not running fine, UL/DL kpi, UL issue values getting for 10 mins instead of 5 mins

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI and UL issue not  running from 20/04/19 00:22.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI and UL issue running fine from 20/04/19 07:17

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but observed double values

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine but observed double values for UL issue service

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine..

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine..

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine..

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine..

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
SS Provisioning service not running.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but SS Provisioning service not running.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but SS Provisioning service not running.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine..

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine...

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine...

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine...

**Comment by swapnildabhole-tm** [comment]
ALL UL/DL KPI AND SS provisioning services are stop

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine..

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine...

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI, UL Issue, UL/DL interferance not running since 23:47

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI, UL Issue, UL/DL interference running since 08:12

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine...
