### ISSUE TITLE
Self Identified: Cambium450iSM devices polling value not showing in performance page from 11:30am 16/04/19

### ISSUE THREAD

**Issue by sarveshreddy-tm** [puneet-tm/wirelessone-support#116]
Customer Live-->Cambium450iSM devices polling value not showing in performance page from 11:30am 16/04/19

**Comment by sohailshaikh-tm** [comment]
Now values are polling for Cambium450iSM devices. Polling is started around 18:00 16/04/19.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

@rohitgupta-tm Please close this issue.
