### ISSUE TITLE
Self Identified: Wirelessone Daily reports Issue

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#117]
No data in daily reports, All daily reports generated blank today except discovery engine reports.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

**RCA:** Issue occurred due to tagging issue in device page.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm please check the RCA and close this bug.
