### ISSUE TITLE
User identified: BH present but missing from BH status page

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#119]
Below IPS  present in BH page but missing from Backhaul utilization status page.

10.175.86.101
--
10.175.87.43
10.193.185.10
172.23.196.130
172.31.180.154
172.31.172.94
172.31.218.38
172.31.211.82
172.31.211.74
172.31.218.34
172.31.233.82
172.23.185.194
172.23.197.66
172.23.197.130
172.23.197.134
10.175.92.116
10.10.10.10
10.226.147.10
10.168.38.9
10.160.227.8
115.114.79.37
172.31.164.170
172.31.167.142

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.
RCA; Issue occurred due to incorrect BH port and BH capacity.
@rohitgupta-tm : please check and close.
