### ISSUE TITLE
Service check-up(JULY)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#128]
Service checking

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA for current service status 09/05/2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3160056/Service.Checkup_Kpi.docx)

**Comment by swapnildabhole-tm** [comment]
HI Team,
PFA Service Status
[Service.Checkup_Kpi(5).docx](https://github.com/puneet-tm/wirelessone-support/files/3160353/Service.Checkup_Kpi.5.docx)

**Comment by santoshkhairnar-tm** [comment]
HI Team,
PFA Service Status of 10/5/2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3164917/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
HI Team,
PFA Service Status of 12/5/2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3169737/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
HI Team,
PFA Service Status of 13/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3171188/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
HI Team,
PFA Service Status of 14/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3175864/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
HI Team,
PFA Service Status of 15/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3180637/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
HI Team,
PFA Service Status of 15/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3180927/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
HI Team,
PFA Service Status of 16/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3185187/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 16/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3185452/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 17/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3189659/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 17/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3189895/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 18/5/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3193569/Service.Checkup_Kpi.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
PFA Service Status of 18/5/2019
[Service.Checkup_Kpi(7).docx](https://github.com/puneet-tm/wirelessone-support/files/3193663/Service.Checkup_Kpi.7.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 19/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3194772/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 20/5/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3196047/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 20/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3196374/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 21/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3200841/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 22/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3205668/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 23/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3210287/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 24/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3214801/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 24/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3215135/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 25/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3219038/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 26/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3219920/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 26/5/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3219994/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 27/5/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3221566/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
PFA Service Status of 27/5/2019
[Service.Checkup(10).docx](https://github.com/puneet-tm/wirelessone-support/files/3221847/Service.Checkup.10.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 28/5/2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3225443/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 29/5/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3230527/Service.Checkup_Kpi.docx)
.

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 30/5/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3235193/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 31/5/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3239448/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 01/6/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3243303/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 01/6/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3243410/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 02/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3244373/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 03/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3245893/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 04/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3250595/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 05/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3255608/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 06/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3260057/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 07/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3264142/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 07/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3264400/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 08/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3268015/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
PFA Service Status of 08/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3268182/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 09/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3269108/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 10/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3270439/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 11/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3274515/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 12/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3279591/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 13/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3284231/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 14/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3289050/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 15/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3292720/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 16/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3293759/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 17/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3295034/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 18/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3299523/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 19/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3304098/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 20/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3308576/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 21/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3312754/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 22/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3316469/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 23/06/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3317425/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 24/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3318958/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 24/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3319277/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 25/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3323287/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 25/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3323600/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 27/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3332957/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 28/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3337561/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 29/06/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3341408/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 30/06/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3342525/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 1/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3343712/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 2/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3348035/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 3/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3353036/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 4/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3357375/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 5/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3360880/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 6/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3364326/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 07
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3365223/Service.Checkup_Kpi.docx)
/07/2019

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 07/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3365286/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 08/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3366423/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 09/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3371223/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 10/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3375769/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
PFA Service Status of 11
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3380000/Service.Checkup_Kpi.docx)
/07/2019

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 11/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3380370/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
PFA Service Status of 12
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3384669/Service.Checkup_Kpi.docx)
/07/2019

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 12/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3384986/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 13/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3388360/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 13/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3388461/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 14/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3389388/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 14/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3389471/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 15/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3390685/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 15/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3390860/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 16/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3394914/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 17/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3399818/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 17/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3400158/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 18/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3404480/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 18/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3404791/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 19/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3409088/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 19/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3409480/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 20/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3413156/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 21/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3414303/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 22/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3415762/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 23/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3420297/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 24/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3425120/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 25/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3429564/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 25/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3429768/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 26/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3433969/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 26/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3434271/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 27/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3437783/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
PFA Service Status of 27/07/2019
[Service.Checkup(1).docx](https://github.com/puneet-tm/wirelessone-support/files/3437862/Service.Checkup.1.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
PFA Service Status of 28/07/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3438794/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 28/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3438860/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 29/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3439895/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 30/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3444874/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 30/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3445238/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 31/07/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3449504/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 31/07/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3450005/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
PFA Service Status of 01/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3454563/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 01/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3454932/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
PFA Service Status of 02/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3564501/Service.Checkup.docx)
