### ISSUE TITLE
User Identified: Customer count showing zero for IM site.

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#131]
Near End BS Name | Customer Count | FAR END BS Name | Customer Count
-- | -- | -- | --
Kranthi complex | 0 | VijayaLakshmi Colony | 15
Ambala Cantt | 0 | SADUNAGAR | 3
New Purshottam Nagar | 0 | Hotel Bandra Residency | 15
DLF New Town (Rajarhat) | 0 | Salt Lake GP 2 | 7

**Comment by rupalivaidya-tm** [comment]
auto ticketing was done for the same with correct customer count.

RCA: Invalid issue

**Comment by rohitgupta-tm** [comment]
RCA: Issue was not handled in W!
