### ISSUE TITLE
Service check-up(August)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#134]
Please share August Service check-up

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 02/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3459677/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 03/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3463386/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 05/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3466017/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 06/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3470108/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 06/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3470399/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 07/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3474947/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 07/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3475284/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 08/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3479538/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 09/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3484486/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 10/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3488516/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 11/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3489509/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 12/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3491172/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 13/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3495048/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 14/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3499543/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 15/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3504066/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 15/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3504330/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 16/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3507816/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 17/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3511596/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 18/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3512635/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 18/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3512700/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 19/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3513931/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 20/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3518748/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 21/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3523576/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 22/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3528295/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 23/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3532549/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 24/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3536777/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 25/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3537776/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 26/08/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3539126/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 27/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3544300/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 28/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3549118/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 29/08/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3553844/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 30/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3558006/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 31/08/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3561998/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Service check-up of 1/09/2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3563036/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Service check-up of 1/09/2019
[Service.Checkup10919.docx](https://github.com/puneet-tm/wirelessone-support/files/3563096/Service.Checkup10919.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Service check-up of 2/09/2019
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3564502/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 3/09/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3567471/Service.Checkup_Kpi.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 4/09/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3572411/Service.Checkup_Kpi.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Service check-up of 4/09/2019
[Current KPI Status.docx](https://github.com/puneet-tm/wirelessone-support/files/3572792/Current.KPI.Status.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Service check-up of 5/09/2019
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3577167/Service.Checkup_Kpi.docx)
