### ISSUE TITLE
Monthly KPI Status Task(August)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#135]
August KPI Status

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Stopped Running Since 04:47Am

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI is Running fine Since 10:02hrs

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI is Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI is Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI is Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI is Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI is Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI is Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI is Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI is Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI is Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI is Running but observing some double values.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI is Running but sometimes observing double values.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
Ul/DL KPI not running

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI not Running

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not Running

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI's not Running.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI's not Running

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI's not Running

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI's not Running

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not Running

**Comment by rupalivaidya-tm** [comment]
UL issue, SS provisioning, UL interference is running since 10:15. But UL/DL utilization KPI not Running

**Comment by rupalivaidya-tm** [comment]
UL/DL utilization KPI Running fine since 11:07hrs

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine but showing double value.
![1](https://user-images.githubusercontent.com/46840979/62621616-f10dd200-b939-11e9-9c67-019458fcde4d.PNG)
![2](https://user-images.githubusercontent.com/46840979/62621618-f10dd200-b939-11e9-8bbf-ed5339f6440e.PNG)

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL kpi running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine since 10:00hrs

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine but UL issue service running stop

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI , UL issue, SS provisioning are Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine. DL interference not running for Some devices of cambium. We are working on it.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL utilization KPI not running. Other services running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not running since 16:42. Other services are running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI , UL Issue, SS provisioning service not running since 17:30

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI , UL Issue, SS provisioning service not running

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI started Running since 7:27 am

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI, UL/DL Intereference, UL Issue service not running since 17:30

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI, UL/DL Intereference, UL Issue service not running

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine since 6:42am

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not running since 16:12. Other services are Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine..

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running but observing double values.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine..

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running except huawei and mrotek

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI not Running from 18:22.

**Comment by rupalivaidya-tm** [comment]
UL/Dl utilization KPI not running. Other KPI services are running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine now

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine now

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but observed double values for UL Issue service.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but observed double values

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but observed some double values

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI, UL Issue service not running and observed double values for ss provisioning & ul/dl interference service

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but observed some double values for ul/dl kpi and ul issue

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine
