### ISSUE TITLE
Weekly Services Check(Status)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#14]
Start Checking the Server(Services) and post the status

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check service status of 23/1/2019.


[Service Check up(KPI).docx](https://github.com/puneet-tm/wirelessone-support/files/2787327/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 24/1/2019.
[Service.Check.up.KPI (1).docx](https://github.com/puneet-tm/wirelessone-support/files/2789053/Service.Check.up.KPI.1.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 24/1/2019.
[Service.Check.up.KPI (1).docx](https://github.com/puneet-tm/wirelessone-support/files/2789952/Service.Check.up.KPI.1.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check current service status of 24/1/2019.

[Service.Check.up.KPI.1.docx](https://github.com/puneet-tm/wirelessone-support/files/2790277/Service.Check.up.KPI.1.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 25/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2793336/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 25/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2794404/Service.Check.up.KPI.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check current service status of 25/1/2019.

[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2794716/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 26/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2797906/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 26/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2798483/Service.Check.up.KPI.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check current service status of 26/1/2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2798623/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check current service status of 28/1/2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2801501/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 28/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2803044/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 28/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2803971/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check current service status of 29/1/2019.
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2808894/Service.Check.up.KPI.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check current service status of 30/1/2019.

[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2810899/Service.Checkup.docx)

**Comment by rohitgupta-tm** [comment]
Please start on New Service check
