### ISSUE TITLE
Weekly KPI Status

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#16]
Please check All the Wirelessone KPI Like : UL/DL and Interfaces services

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running Fine

**Comment by puneet-tm** [comment]
@rohitgupta-tm @sarveshreddy-tm @sohailshaikh-tm @rupalivaidya-tm @swapnildabhole-tm @santoshkhairnar-tm  All are requested to provide in details status on this task, even if all services are running.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running Fine.

@rohitgupta-tm @sarveshreddy-tm @sohailshaikh-tm @rupalivaidya-tm @santoshkhairnar-tm

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI not running from 13:52

@rohitgupta-tm @sohailshaikh-tm @rupalivaidya-tm @santoshkhairnar-tm @swapnildabhole-tm

**Comment by sarveshreddy-tm** [comment]
KPI Running Fine from15:17

**Comment by sarveshreddy-tm** [comment]
KPI Running Fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running Fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI and Interference running fine @rohitgupta-tm @sarveshreddy-tm @sohailshaikh-tm @rupalivaidya-tm @swapnildabhole-tm

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running Fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running Fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running Fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running Fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/ DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/ DL KPI not running since 14:47

**Comment by santoshkhairnar-tm** [comment]
UL/ DL KPI running from 17:37

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running Fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UP/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sarveshreddy-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not working since 13:52 on 29/09/2019

**Comment by rohitgupta-tm** [comment]
KPI working now
