### ISSUE TITLE
Weekly Services Check(Status)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#24]
Please share the service status on daily basis here

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please find services checkup
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2812507/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find services checkup
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2813715/Service.Check.up.KPI.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please find services checkup
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2815708/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2817610/Service.Check.up.KPI.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2820157/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2821531/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2824028/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2824349/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2825220/Service.Check.up.KPI.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2825452/Service.Check.up.KPI.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2826403/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2826657/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2830621/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Current services checkup,
[Service.Check.up.KPI.docx](https://github.com/puneet-tm/wirelessone-support/files/2830804/Service.Check.up.KPI.docx)
