### ISSUE TITLE
self identified : BS Dump generation failure from 25 Jan 2019

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#25]
BS Dump report was not generated since 25-01-2019.

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Issue is resolved now and BS Dump is generated.
RCA: Issue was occurring due to incorrect RFS date in Inventory Sector.

**Comment by rohitgupta-tm** [comment]
Ok.
Correct RCA.
Team please start report bug here also
