### ISSUE TITLE
Notified by User : BH Utilization report failure 

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#26]
Hello Team,

Below Switch is responding to the SNMP but utilization values not coming on wirelessone, please check below snapshot for the same,

Switch IP: 10.175.87.44

![image](https://user-images.githubusercontent.com/46840748/51984154-a4e06180-24c0-11e9-8160-f3a242b5c40d.png)

**Comment by puneet-tm** [comment]
@rohitgupta-tm where is the resolution/updates for this issue?

**Comment by sohailshaikh-tm** [comment]
Utilization values are coming for above case but kpi's not running for the same.

**Comment by sohailshaikh-tm** [comment]
Adding more cases in this with BH utilization failure report,

Please refer 'Comment' in attached BH Utilization failure report for the Issues.
[BH polling failure.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2817704/BH.polling.failure.xlsx)

**Comment by rohitgupta-tm** [comment]
hello Team,
Any update about KPI, it is still not working?

**Comment by sohailshaikh-tm** [comment]
Utilization kpi is running fine for Switch IP: **10.175.87.44**, please check below snap for the same,
![image](https://user-images.githubusercontent.com/46840748/52160892-4941ee00-26e3-11e9-88bb-640795dbbf67.png)

**Comment by puneet-tm** [comment]
@sohailshaikh-tm @rohitgupta-tm what was the RCA?

**Comment by sohailshaikh-tm** [comment]
Not getting BH utilization graph over W1 for the below mentioned Huawei switches.
[Huawei Switches.docx](https://github.com/puneet-tm/wirelessone-support/files/2832049/Huawei.Switches.docx)

**Comment by santoshkhairnar-tm** [comment]
Utilisation graph is coming for mentioned huawei switches.
RCA: There is some issue in KPI services for new added devices because devices not considered in kpi sync. 

Subhash done some changes in kpi sync for this issue #
