### ISSUE TITLE
Notified by User: 10.110.137.13--Customer live UAS and Performance polling value not matching.

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#27]
Hello team,

Customer live UAS and Performance polling value not matching.

![image001 1](https://user-images.githubusercontent.com/46840748/52062711-0c68e080-2597-11e9-8a96-5cc8199a7a6d.png)
![image002](https://user-images.githubusercontent.com/46840748/52062678-fc510100-2596-11e9-9803-cf79ff341a61.png)

**Comment by sohailshaikh-tm** [comment]
Issue has been resolved now, values are matching now, please check below snaps:

![image](https://user-images.githubusercontent.com/46840748/52062951-84cfa180-2597-11e9-84db-aa833330a740.png)
![image](https://user-images.githubusercontent.com/46840748/52062978-9749db00-2597-11e9-87ad-0d8bc3268ab1.png)

**Comment by puneet-tm** [comment]
@santoshkhairnar-tm @rohitgupta-tm what was the RCA?

**Comment by rohitgupta-tm** [comment]
RCA: This issue is because of two entry was present in performance table and we are taking old value for that IP
