### ISSUE TITLE
Notified by User: PE Hostname is not available in download report for PE Listing

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#28]
PE Hostname is not available in download report for PE Listing : Performance Reports> PE

**Comment by santoshkhairnar-tm** [comment]
Issue Resolved, PE hostname available in download report.

**Comment by puneet-tm** [comment]
@santoshkhairnar-tm @rohitgupta-tm what was the RCA??

**Comment by rohitgupta-tm** [comment]
This is very old issue which was not found in Daily Health check-up to.
RCA: Column is not added in Report
