### ISSUE TITLE
Self Identified : Aging issue in Capacity Management

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#29]
Hello Team,
Please check Capacity Management  and share your updates

**Comment by sohailshaikh-tm** [comment]
Aging values are not coming for following modules:

1. Capacity management->Daily Alerts->Sector Augmentation->**Cambium**
2. Capacity management->Daily Alerts->**Backhaul Augmentation**

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm -- please share RCA

**Comment by rohitgupta-tm** [comment]
RCA : We have change the code for the aging calculation.
