### ISSUE TITLE
Self Identified: Error while applying filter on Status since, Timestamp, value, Data source name columns in Network Details

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#31]
Getting an error message "DataTables warning: table id=network_pmp_ul_interference_block_table - list index out of rangelist index out of range" while applying filter on "Status since, Timestamp, value, Data Source name" column in:
Alert Center**->**Alert Details**->**Network Alert Details**->**
PTP BH/Wimax BS/PMP BS/WiMAX Temp./BH Temp./Cambium DL Interference/Cambium UL Interference/AP Frame Utilization  

Snaps:
![image](https://user-images.githubusercontent.com/46840748/52173788-dacb6180-27b0-11e9-969f-0fc9c06265d3.png)
![image](https://user-images.githubusercontent.com/46840748/52173789-e585f680-27b0-11e9-8b7e-fe471c75eaf0.png)
![image](https://user-images.githubusercontent.com/46840748/52173795-f0d92200-27b0-11e9-9a7b-543935cc2eaf.png)

**Comment by santoshkhairnar-tm** [comment]
Issue Resolved, we are able to search applying filter Status since, Timestamp, value, Data source name columns in Network Details in Alert Center.

**Comment by rohitgupta-tm** [comment]
RCA: This is the post-deployment issue.
