### ISSUE TITLE
Self identified: Status Since Column Blank

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#33]
Not getting values in Status Since for the following modules:

Alert Center->Alert Details->Network Details->(Cambium DL Interference, Cambium UL Interference, Wimax UL Issue, Cambium UL Issue, AP Frame Utilization)

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

**RCA**: Code Issue (Code corrected by Subhash).
