### ISSUE TITLE
Self Identified: Discovery Engine Reports not generated

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#34]
Discovery Engine Reports not generated since 3 Feb 2019

**Comment by rupalivaidya-tm** [comment]
Issue resolved.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm -- please  share RCA

**Comment by rohitgupta-tm** [comment]
RCA: We are getting some issue in data insertion.
