### ISSUE TITLE
Self identified: Customer RF health Report Issue

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#35]
3-Feb 4pm & 4-Feb 11am Customer RF health Report generated blank.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm -- please share RCA .

**Comment by rohitgupta-tm** [comment]
RCA : Data not present on Reporting server at for that time
