### ISSUE TITLE
Notified by User: BHWise Topology Count Report Issue

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#36]
Radwin5k-GSU  Count is incorrect in BHWise Topology Count Report.

**Comment by rohitgupta-tm** [comment]
Hello Team,
Please update

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Dushyant sir will resolve this issue at the end of this week.

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Dushyant sir will resolve this issue at the end of tomorrow.

**Comment by rohitgupta-tm** [comment]
RCA: We are taking GSU as per sector ID. In this case, if there is 3 sector present on BS then GSU will be 3.
which is resolved now we are taking unique value.
