### ISSUE TITLE
Notified by User: INCC not generated for SA BS || 10.131.212.9/10

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#43]
INCC is not auto generated for 10.131.212.9/10 which is down since 03/02/19 07:20 AM.

**Comment by santoshkhairnar-tm** [comment]
This is   PTPBH case which is resolved in last deployment

**Comment by rupalivaidya-tm** [comment]
**RCA:**  This case was not handled in previous deployment and handled in latest deployment. Issue Resolved.
@rohitgupta-tm : Please check the RCA and close this issue.

**Comment by rohitgupta-tm** [comment]
RCA : This case was not handled in W1, and this case handled in last deployment
