### ISSUE TITLE
Notified by User: Wrong customer count is reported in BS dump

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#44]
Zero customer count is showing for Radwin5k JET in BS dump for below cases.
[Book1.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2832056/Book1.xlsx)

**Comment by rohitgupta-tm** [comment]
@sohailshaikh-tm Please assign labels,assignees,project,milestone while creating bug/task

**Comment by santoshkhairnar-tm** [comment]
**RCA:**This issue is because those devices is not added to nms_monotoring.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm : Please Check the RCA and close this issue.

**Comment by rohitgupta-tm** [comment]
Correct RCA
