### ISSUE TITLE
Alert Centre Down Tab - Not showing current down Devices & INCC not creating

### ISSUE THREAD

**Issue by sarveshreddy-tm** [puneet-tm/wirelessone-support#45]
Current Down Device not reflecting in Alert Center down Tab. Ticking not not working since 7:41Am Today

**Comment by puneet-tm** [comment]
@sarveshreddy-tm Please assign Project and Milestone as well whenever you are opening a bug. Also Please mention "Notified by User" or "Identified by Me" to each bug in the starting of subject line.

**Comment by sarveshreddy-tm** [comment]
ok Sir

**Comment by puneet-tm** [comment]
@sarveshreddy-tm @rohitgupta-tm Milestones will always be in Month format and the same will always be created by Rohit or me only. You just need to assign the bug to the current milestone.

**Comment by rohitgupta-tm** [comment]
This issue is because of patching activity.
