### ISSUE TITLE
Self Identified: Unable to search uploaded Devices with IP

### ISSUE THREAD

**Issue by sarveshreddy-tm** [puneet-tm/wirelessone-support#47]
Unable to search uploaded devices with IP, with BS name able to search. Following are samples

![image](https://user-images.githubusercontent.com/46859152/52519866-030f0080-2c88-11e9-9211-571102f8ba42.png)

10.226.19.2
10.226.19.3
10.162.62.6
10.162.62.7
10.162.62.9
10.227.64.2
10.227.64.3
10.227.64.4
10.110.87.3
10.110.87.4
10.110.87.5
10.227.51.2
10.227.51.3
10.227.51.4
10.157.206.6
10.157.206.7
10.157.206.8
10.226.172.2
10.226.172.3

**Comment by rohitgupta-tm** [comment]
RCA : Bulk-Upload issue
