### ISSUE TITLE
Self Identified: KPI not running for devices uploaded on 8th Feb, UL/DL running

### ISSUE THREAD

**Issue by sarveshreddy-tm** [puneet-tm/wirelessone-support#48]
Devices KPI not running device uploaded on 8th jan , but utilization running properly. 

10.226.19.2
--
10.226.19.3
10.162.62.6
10.162.62.7
10.162.62.9
10.227.64.2
10.227.64.3
10.227.64.4
10.110.87.3
10.110.87.4
10.110.87.5
10.227.51.2
10.227.51.3
10.227.51.4
10.157.206.6
10.157.206.7
10.157.206.8
10.226.172.2
10.226.172.3

**Comment by rohitgupta-tm** [comment]
RCA: Devices are not getting synced.
