### ISSUE TITLE
Wirelessone was working slow

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#5]
@rohitgupta-tm 
wirelessone was working slow in between 10 pm to 10:30 pm today,
now w1 is working fine

**Comment by puneet-tm** [comment]
@sohailshaikh-tm @rohitgupta-tm Please assign project and milestone as well whenever you create an issue. Also, write "Notified by User" or "Self Identified" in the starting of the subject whenever you create a bug.

**Comment by rohitgupta-tm** [comment]
Thanks Sohail
