### ISSUE TITLE
Notified by User: No TT for IM site_Manvi (10.197.200.9)

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#50]
Got TT of far end (Manvi_Fire_Station_Road (10.197.200.10) ) but no TT  generated & no down alarm obtained  in W1 for IM site (Manvi (10.197.200.9))

**Comment by sohailshaikh-tm** [comment]
IM site is also not coming in down tab.

User provided examples:
10-‎02-‎2019 07:15]  RF Noc:  
10.197.200.10 
10.197.200.9 
 
[‎10-‎02-‎2019 07:25]  RF Noc:  
10.170.166.10 
CHETNA 
10.175.147.7

**Comment by rupalivaidya-tm** [comment]
**RCA:** Issue occurred due to PTP BH wrong Inventory.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm : please check and close this issue.

**Comment by rohitgupta-tm** [comment]
RCA : Inventory Issue
