### ISSUE TITLE
Self Identified : Reporting issue (Incorrect Data)

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#56]
Hi Team,
Observed incorrect data in following reports:

**1)**Download Center/   Customer Reports/ Modulation Report ||||| Modulation type count incorrect for   Radwin5K, cambium450i, cambium450m,Radwin5k-jet
-- | --
**2)**Download Center/   Customer Reports/ / Rectification Report ||||| Incorrect los/rogue/normal count   for wimax, cambium, increment in crc error column blank for Radwin5k &   Radwin5k-jet, los/uas/normal count incorrect & far end rssi 0 value for   PTP
-- | --
**3)**Download Center/   Customer Reports/Latency Report |||||| Incorrect Count of avg. latency
-- | --
**4)**Download Center/   Customer Reports/ Customer Beacon Daily Report ||||| Incorrect count of beacon in Daily and weekly report for 10/02/2019
-- | --
**5)**Download Center/   Network Reports/ UL issue Report ||||| Incorrect count for cambium
-- | --
**6)**Download Center/   Customer Reports/ SMRSSIVariationReport ||||| 0 value coming for 9/2/2019
-- | --
**7)**Download Center/   Customer Reports/  Radwin 5k CRC Error   Report ||||| Data not generated for 9/2/2019
-- | --

**Comment by rohitgupta-tm** [comment]
RCA : Reporting path has been changed due to activity
