### ISSUE TITLE
Notified by user: RADWIN JET HBS UTILISATION NOT GETTING CAPTURED ON W1

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#57]
Radwin5K-JET utilization is not getting captured on W1
JET HBS: 10.194.120.3

**Comment by rohitgupta-tm** [comment]
@rupalivaidya-tm Please update

**Comment by rupalivaidya-tm** [comment]
Issue resolved from our end.
This issue is pending from user side. Awaiting for further update from user.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm : Please close this issue.

**Comment by rohitgupta-tm** [comment]
Closing this issue as we are not getting any further update from the user.
