### ISSUE TITLE
Notified by user: BS DUMP-DISCREPANCY IN REGION NOMENCLATURE

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#58]
Latest BS dump attached showing discrepancy in nomenclature of Region column i.e  in Cambium100/Radwin5K/Cambium450i/Radwin5K-Jet all are having “/”  in them (For eg- PB/HR/HP/J&K) while as per standard nomenclature it should be separated by  “-“  which is only seen in Cambium450m dump.

**Comment by rohitgupta-tm** [comment]
RCA: Not an issue
