### ISSUE TITLE
Notified by user: INCC not generated for SA BS || Parvati Plaza_10.169.243.10

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#59]
INCC was not auto fired for subjected BS even the customer count is 4. 
Kindly check and share your observations.

**Comment by santoshkhairnar-tm** [comment]
RCA: As this is PTP BH far end base as per latest wirelessone inventory we don’t use  any pop conveter ip and aggregation ip for backhaul. / Resolved

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.
@rohitgupta-tm : Please close this issue.
