### ISSUE TITLE
Notified bu user:Email Notification-Grren event missing-INCC04021914082-Babnan,10.139.147.10

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#60]
Please check as Green event is missing for the Attached Red event today.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm : RCA needed

**Comment by rohitgupta-tm** [comment]
RCA: There is some delay in Email sending(Timeout error) which is corrected in activity
