### ISSUE TITLE
Notified by User: RR Nagar#ARMMOR INCC not auto fire

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#67]
Kindly share the observation on below two scenario.

1. Customer count 5 then why INCC not auto fired for RR Nagar BS.
2. As RR nagar is FAR end BS & ARMMOR BTS is IM then why customer count not floated on IM site BS.
![screen shot 2019-02-15 at 10 38 45 pm](https://user-images.githubusercontent.com/46840748/52952132-b45d1700-33a9-11e9-9891-28596f83fb2b.png)
![screen shot 2019-02-15 at 10 36 59 pm](https://user-images.githubusercontent.com/46840748/52952188-d9ea2080-33a9-11e9-92ee-ce4578189d8e.png)

**Comment by sohailshaikh-tm** [comment]
Issue has resolved.
**RCA:** This issue is because Customer count showing Zero( 0 ) for ARMMOR which was because of the inventory.
As we checked in Base Station Page  BS Name is RR NAGAR(All caps) but in Circuit page we found Name as RR Nagar which cause error while fetching the Customer Count.
We have made some changes in Circuit page and Customer count is correct.

**Comment by puneet-tm** [comment]
@sohailshaikh-tm Were these your findings or @rohitgupta-tm helped you in this?

**Comment by sohailshaikh-tm** [comment]
@puneet-tm Hello Sir,
These are Rohit's findings.

**Comment by puneet-tm** [comment]
@rohitgupta-tm Good Work.

**Comment by rohitgupta-tm** [comment]
@puneet-tm thank you sir
