### ISSUE TITLE
Notified by User: OR01340_Ekatali-Auto ticket not generated-10.131.114.2

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#68]
Subjected sector OR01340_Ekatali (10.131.114.2) was down for 40 mins but INCC did not get fired.

Instead an incorrect incident is showing for the subjected sector.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

**RCA:** This incident happened because of manual provoke ticketing.
Someone fired ticket from manually provoke on 9th February 2019.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm : Please check RCA and close the issue.

**Comment by rohitgupta-tm** [comment]
**RCA:** This incident happened because of manual provoke ticketing.
Someone fired ticket from manually provoke on 9th February 2019 which was not cleared so this issue occur.
