### ISSUE TITLE
Notified by User: NO CRITICAL EVENT AND RE/GE FOR INCC_INCC15021926747

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#69]
Only clear event in history dump and critical event is missed. Also no RE an GE for same.

**Comment by rupalivaidya-tm** [comment]
Monolith Issue.
RCA: monolith database Ticket ID : INCC15021926663 was opened for alarmID 48444af4-a5d6-44c1-b230-5e69951c73df with IP 10.226.172.3 & Ticket ID INCC15021926664  was opened for alarmID 21a05f10-5605-4392-b2e4-f004f06098f2 with IP 10.156.209.10

**Comment by rohitgupta-tm** [comment]
Due to manual provoke ticketing
