### ISSUE TITLE
Self Identified: HTTP flag on W1

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#71]
HTTP FLAG ISSUE

**Comment by rohitgupta-tm** [comment]
we have done the changes on UAT and tested

**Comment by rohitgupta-tm** [comment]
We will deploy this on Prod by this week

**Comment by rupalivaidya-tm** [comment]
We will deploy this on Production by this weekend .

**Comment by santoshkhairnar-tm** [comment]
As discussed with rohit, we will deploy this on production on  9th march saturday because resources not available.

**Comment by rupalivaidya-tm** [comment]
We will deploy this on production on 9th march saturday because resources not available.

**Comment by rohitgupta-tm** [comment]
We have implemented the https flag on production
