### ISSUE TITLE
Notified by User: INCC not generated automatically for Barwala (10.226.252.10)

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#74]
NCC was not auto fired for subjected BS even the customer count is 1.

DOWN at 24/02/19 23:50
BS Name : Barwala (10.226.252.10)

**Comment by santoshkhairnar-tm** [comment]
Invalid issue,  because of circuit id is M6_NA so that was ticket not autofired.
