### ISSUE TITLE
Notified by User: W1 FRAMEWORK INVENTORY NOT GETTING UPDATE

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#75]
Observed W1 inventory is not reflecting actual framework.
HBS was upgraded on .84 framework on 20-Feb 19 but after 5 days still W1 is showing old framework (.82)

Case: BILASPUR_1 (10.134.13.2)

**Comment by rohitgupta-tm** [comment]
We are checking for more live cases till Monday

**Comment by sohailshaikh-tm** [comment]
Currently the values is coming right for device 10.134.13.2 (last polled value 01/03/19 16:30)
Updated value is reflecting on w1 from 26-02-2019 , but for date 27 & 28 Feb value is missing for the same device

**Comment by rohitgupta-tm** [comment]
Closing this issue because we did not get any live cases from user
