### ISSUE TITLE
User notified: Ascending/Descending function is not working for packet loss

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#76]
Ascending/Descending function is not working for packet loss in performance reports for both network and customer live.
PFA of screenshot
![capture](https://user-images.githubusercontent.com/46848629/53496485-25967b80-3ac8-11e9-82b0-095fecde32c8.PNG)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Rupam is checking this issue and will revert till tomorrow.

**Comment by rohitgupta-tm** [comment]
We will do this by Tuesday

**Comment by rupalivaidya-tm** [comment]
This issue will be resolved by Tuesday.

**Comment by rupalivaidya-tm** [comment]
This issue will be resolved by Tomorrow.

**Comment by rupalivaidya-tm** [comment]
We need Downtime of 1 hr for this issue. 
@rohitgupta-tm : Please confirm the date for the same.

**Comment by rupalivaidya-tm** [comment]
Tentative Date: 16-03-2019.

**Comment by rupalivaidya-tm** [comment]
Work around has been done. Issue under observation.

**Comment by rohitgupta-tm** [comment]
This is the after deployment issue.
