### ISSUE TITLE
KPI not running,sudo service snmptt status not run on clprd7(Public Poller),Sync not run by discovery: Self Identified

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#8]
@rohitgupta-tm 1)KPI not running for both network and customer live, 2)sudo service snmptt status not run on clprd7(Public Poller) after activity, 3)Today Sync not run by discovery yesterday sync status pending run by Basant.

**Comment by rohitgupta-tm** [comment]
Resolved
