### ISSUE TITLE
Service check-up(Monthly)

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#80]
Please share service check-up here till 31 March

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2921762/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 03-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2922773/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 03-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2923379/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 04-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2924361/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 04-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2927452/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 05-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2928992/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 05-03-2019. Services are workinf fine since 10:22.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2929497/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 06-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2934055/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 06-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2934430/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 07-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2939202/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 07-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2939556/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 08-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2944174/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 08-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2944418/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 09-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2947987/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 10-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2949073/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 11-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2950707/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 12-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2955186/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 13-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2959468/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 13-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2959807/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 14-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2964382/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 14-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2964749/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 15-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2969198/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 15-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2969473/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 16-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2973374/Service.Checkup_Kpi.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Please find server checkup Status 
[Server.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2973483/Server.Checkup.docx)
for 16-03-2019.

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 17-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2974696/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 17-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2974824/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 18-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/2976150/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 18-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2976407/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 19-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2981703/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 21-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2990926/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 22-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2994704/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 22-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2995036/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 23-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2998926/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Please check services checkup status of 23-03-2019.
[Service.Checkup(1).docx](https://github.com/puneet-tm/wirelessone-support/files/2999010/Service.Checkup.1.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 24-03-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/2999984/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 24-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3000056/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 25-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3001245/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 25-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3001580/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 26-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3006222/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 26-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3006536/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 27-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3011207/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 27-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3011517/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 28-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3016210/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 29-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3021148/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 30-03-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3025149/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 31-03-2019.
UL/DL KPI Not running
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3026157/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 31-03-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3026226/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 1-04-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3027566/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Please check services checkup status of 1-04-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3027817/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 2-04-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3032128/Service.Checkup.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Please check service checkup of 2 Apr 2019
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3032337/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 3-04-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3036582/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 3-04-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3036885/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 4-04-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3041444/Service.Checkup_Kpi.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 4-04-2019.
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3041798/Service.Checkup.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please check services checkup status of 5-04-2019.
[Service.Checkup_Kpi.docx](https://github.com/puneet-tm/wirelessone-support/files/3046084/Service.Checkup_Kpi.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 6-04-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3050172/Service.Checkup.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 07-04-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3051200/Service.Checkup.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please check services checkup status of 09
[Service.Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3056899/Service.Checkup.docx)
-04-2019.

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please check services checkup status of 09-04-2019.
[Service Checkup.docx](https://github.com/puneet-tm/wirelessone-support/files/3057196/Service.Checkup.docx)
