### ISSUE TITLE
Monthly KPI Status Task

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#84]
Hello Team,
Please share monthly KPI status here

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but sometimes value double or comes after 10 mins.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI Running fine.

**Comment by sohailshaikh-tm** [comment]
Observing Interference double value of Interference for network devices (22:32 value)
UL/DL KPI Running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI not running from 03:42

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI,ul issue,Intereference not running

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI,UL issue, Interference not running.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI, ul issue ,Interference running fine since 10:22

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
Ul/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine. 
Double values for UL Issue and ss provisioning service .

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but sometimes UL/DL Kpi service values coming after 10 mins

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.
UL interference value double at 16:32

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI Running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
Observing double values of UL/DL KPI services

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI, UL Issue, ss provisioning services values coming for 10 or 15 min instead of each 5 min, some times getting double value for the same and also observing double value for UL/DL Intereference

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not running since 9:27.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine since 10:37

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
Double values for UL/DL KPI's

**Comment by rupalivaidya-tm** [comment]
Double values for UL/DL KPI's

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI's  are running fine. But getting double values.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI's are running fine. But getting double values.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI not running since 9:02.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI started running from 10:27 am

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine since 10:27.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running but observed double values for network live>Wimax,  customer live> radwin5k

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI service not running.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI service not running.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
Ul/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL kpi running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL kpi running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI not running from 02:37.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running from 08:17 AM

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI Running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine but UL Issue values coming double for both network and customer devices.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine but observed double values for 7:17

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
Multiple same values Issue observed in UL/DL KPI value. Observed same 5 times value for 8:27 am

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by swapnildabhole-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
Getting double values for UL/DL KPI service.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by santoshkhairnar-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by rupalivaidya-tm** [comment]
UL/DL KPI running fine.

**Comment by sohailshaikh-tm** [comment]
UL/DL KPI running fine.
