### ISSUE TITLE
Notified by user: SECTOR DUPLICITY : KARKAR TOLA BS :10.191.36.11

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#85]
Observing sector duplicity on subjected BTS, One is showing (5) customers and second is showing (0) customer, but only Performance reports- n/w live- Radwin 5k, but not in sector or BS page.

**Comment by rupalivaidya-tm** [comment]
Update need to confirm from developer's side. We will get it on Monday.

**Comment by rupalivaidya-tm** [comment]
Rupam Is checking this issue and will update soon.

**Comment by rupalivaidya-tm** [comment]
Issue is resolved.
**RCA:** Issue occurred due to double entry of same sector in Database. Issue resolved post deleting one of them (with wrong customer count=0).

@rohitgupta-tm Please close this issue.

**Comment by rohitgupta-tm** [comment]
RCA: duplicate entry present in sectoridwisecustomercount table for one sector
