### ISSUE TITLE
Notified by User: Incident | Janta Colony:10.189.141.4 sector INCC generated

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#86]
As per W1, sector is showing down Janta Colony:10.189.141.4 at 4:20 to 4:45 AM today (03/03/19).
INCC is triggered for same .but we get the ping response and login into sector that time.

INCC: INCC02031912342

**Comment by sohailshaikh-tm** [comment]
On W1 packet drop was 100 from time 4:20 to 4:45
![image](https://user-images.githubusercontent.com/46840748/53697521-efbf0300-3df7-11e9-9fb6-daa47e516112.png)

Also observing issue in device uptime value of the same device which is not changing for continuous 40-45 mins 
device uptime snap ->
![image](https://user-images.githubusercontent.com/46840748/53697652-93f57980-3df9-11e9-9ac2-3e237dd55e9d.png)

**Comment by rupalivaidya-tm** [comment]
This device might not be responding from wirelessone poller that time. Device was up and responding from poller when issue is notified to us.

@rohitgupta-tm please close this issue.
