### ISSUE TITLE
User Notified: Device Up in Network but Down in Wirelessone, Device Down in Network but Up in Wirelessone.

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#88]
Issue observed as if some Device Up in Network shows Down in Wirelessone and if some Device Down in Network but Up in Wirelessone

**Comment by puneet-tm** [comment]
Looks like ospf6_slave_1 is having some constraints in running checks and hence delay is seen in the polling of devices.
Siddhika is looking into the issue as per the lead provided by me to her for Checks/Nagios Level Delay Issue.

**Comment by sohailshaikh-tm** [comment]
Issue is resolved.
Need RCA

**Comment by rohitgupta-tm** [comment]
Duplicate issue: issue in ospf6_slave1
