### ISSUE TITLE
Notified by User: On application server inpudimnrfcmprd1 /apps directory usage crossed threshold value

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#89]
/apps directory on inpudimnrfcmprd1 is now 89% used

**Comment by sohailshaikh-tm** [comment]
/apps directory usage on inpudimnrfcmprd1 is now under threshold i.e. 63%
snap:
![image](https://user-images.githubusercontent.com/46840748/54055473-330fdc00-4213-11e9-9fb7-b0d592e465eb.png)

**Comment by rohitgupta-tm** [comment]
RCA: this is because log files are present on /apps folder which is consuming space
