### ISSUE TITLE
Handover L1 Support Pune

### ISSUE THREAD

**Issue by rohitgupta-tm** [puneet-tm/wirelessone-support#9]
Daily Handover

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please find handover sheet.

[Daily Handover.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2778769/Daily.Handover.xlsx)

**Comment by rohitgupta-tm** [comment]
@swapnildabhole-tm where is your Handover?

**Comment by sarveshreddy-tm** [comment]
[Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2779924/Handover.docx)
Hi Team PFA for Handover
@rohitgupta-tm @rohitgupta-tm @rupalivaidya-tm @sohailshaikh-tm @swapnildabhole-tm

**Comment by santoshkhairnar-tm** [comment]
Hi Team please find handover sheet
@rohitgupta-tm @rupalivaidya-tm @sarveshreddy-tm @sohailshaikh-tm @swapnildabhole-tm 
[Handover sheet.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2781116/Handover.sheet.xlsx)

**Comment by rupalivaidya-tm** [comment]
Hi Team, Please find Handover Sheet.
@rohitgupta-tm @sarveshreddy-tm @santoshkhairnar-tm @sohailshaikh-tm @swapnildabhole-tm 

[Daily Handover.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2782520/Daily.Handover.xlsx)

**Comment by swapnildabhole-tm** [comment]
Hi Team, Please Find Handover Sheet.
@rohitgupta-tm @rupalivaidya-tm @santoshkhairnar-tm @sohailshaikh-tm @sarveshreddy-tm 
[Daily Handover.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2782593/Daily.Handover.xlsx)

**Comment by sarveshreddy-tm** [comment]
Hi Team,

Please find Handover shit.

[Handover 22.docx](https://github.com/puneet-tm/wirelessone-support/files/2783941/Handover.22.docx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,

Please find Handover sheet.
[Handover.23.docx](https://github.com/puneet-tm/wirelessone-support/files/2785444/Handover.23.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please find Handover sheet.

[Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2787413/Handover.docx)

**Comment by swapnildabhole-tm** [comment]
Hi team,

Please find Handover sheet.
[Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2787513/Handover.docx)

@rohitgupta-tm @rupalivaidya-tm @sarveshreddy-tm @santoshkhairnar-tm @sohailshaikh-tm

**Comment by sarveshreddy-tm** [comment]
Hi team,

Please find Handover sheet.

[Work Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2788286/Work.Handover.docx)

**Comment by sohailshaikh-tm** [comment]
Hi team,

Please find Handover sheet.
[Handover 24.docx](https://github.com/puneet-tm/wirelessone-support/files/2789996/Handover.24.docx)

**Comment by rupalivaidya-tm** [comment]
Hi team,
Please find Handover sheet.

[Daily Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2791587/Daily.Handover.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi team,
Please find Handover sheet.
[Handover sheet.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2792757/Handover.sheet.xlsx)

@rohitgupta-tm @sarveshreddy-tm @rupalivaidya-tm @sohailshaikh-tm @swapnildabhole-tm

**Comment by sohailshaikh-tm** [comment]
Hi team,
Please find Handover sheet.
[Handover.23.docx](https://github.com/puneet-tm/wirelessone-support/files/2794464/Handover.23.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
Please find Handover Sheet.

[Daily Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2795916/Daily.Handover.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,


Please find handover sheet.

________________________________

**Comment by swapnildabhole-tm** [comment]
Hi Team,
Please find Handover sheet.
[Daily Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2795951/Daily.Handover.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please find Handover sheet.

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
Please find Handover sheet.
[Handover sheet.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2797138/Handover.sheet.xlsx)

**Comment by sohailshaikh-tm** [comment]
Hi Team,
Please find Handover sheet.
[Handover 24.docx](https://github.com/puneet-tm/wirelessone-support/files/2798494/Handover.24.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team,
please find Handover sheet.
[handover260119.docx](https://github.com/puneet-tm/wirelessone-support/files/2798918/handover260119.docx)

**Comment by rupalivaidya-tm** [comment]
Hi Team,
please find Handover sheet.
[Daily Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2798927/Daily.Handover.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team,
please find Handover sheet.
[Handover sheet.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2799277/Handover.sheet.xlsx)

**Comment by sarveshreddy-tm** [comment]
Hi Team, Please Find Handover Sheet.
[Work Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2799725/Work.Handover.docx)

**Comment by swapnildabhole-tm** [comment]
Hi Team, please find Handover sheet.
[Work.Handover (1).docx](https://github.com/puneet-tm/wirelessone-support/files/2799982/Work.Handover.1.docx)

**Comment by santoshkhairnar-tm** [comment]
Hi Team, please find Handover sheet.
[Handover  @sheet.xlsx](https://github.com/puneet-tm/wirelessone-support/files/2800272/Handover.sheet.xlsx)

**Comment by sarveshreddy-tm** [comment]
Hi Team,

Please find work handover


[Work Handover.docx](https://github.com/puneet-tm/wirelessone-support/files/2801260/Work.Handover.docx)

**Comment by swapnildabhole-tm** [comment]
Hi team,

please find the handover sheet.
[Handover28-0119.docx](https://github.com/puneet-tm/wirelessone-support/files/2802569/Handover28-0119.docx)

**Comment by rohitgupta-tm** [comment]
Hello Team,
I have checked the handover sheet and found 2 issue was resolved so please update and share in latest sheet
