### ISSUE TITLE
Self Identified: KPI was not working

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#91]
KPI was not working on Saturday (09/03/19) between 9:30 am to 10:30 am.

**Comment by santoshkhairnar-tm** [comment]
Issue was resolved, KPI working from 09/03/19 10:32
RCA: KPI services not running, Services start by developer

**Comment by rohitgupta-tm** [comment]
RCA: Issue is because sarvesh stop the cmprd1 so KPI get stopped
