### ISSUE TITLE
User Notified : Sector Unreachable issue in W1 || DOGACHHIAA_10.135.215.2

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#92]
Observing as per w1 sector is unreachable but we are getting ping response at the same time. INCC(INCC07031917205) got fired for the same.

**Comment by santoshkhairnar-tm** [comment]
Restart some services for resolve this issue

**Comment by rupalivaidya-tm** [comment]
Work around done. Issue under observation.

**Comment by rohitgupta-tm** [comment]
RCA: Duplicate issue.
This issue is because of ospf6_slave.
