### ISSUE TITLE
User Notified: Duplicate sector ID and wrong sector count for WiMAX ODU alerts

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#96]
Observing duplicate sector ID and wrong sector count for WiMAX ODU alerts.

**Comment by rupalivaidya-tm** [comment]
Duplicate sector id comes because of the inventory.Duplicate sector present in Inventory

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

@rohitgupta-tm : Please share RCA and close this issue.

**Comment by rohitgupta-tm** [comment]
RCA: Inventory issue
