### ISSUE TITLE
Notified by User: INCC GENERATED FOR CONVERTOR INSTEAD OF SWITCH

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#97]
INCC is generated for BS convertor (10.156.44.10) BRY_Bellary-Hospet Road ,as its aggregation switch (10.175.32.210) is down. 
Please check and confirm why INCC is not generated for switch. 
  
Kindly refer INCC :- INCC17031910917

**Comment by rohitgupta-tm** [comment]
RCA: one service on ospf6_slave1 was stopped due to which polling get affected.
