### ISSUE TITLE
Notified by User: CSP Customer cases ticket in History Tab | Network alert center

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#98]
Please check as how we are getting CSP customer tickets in History Tab | Network alert center

**Comment by rupalivaidya-tm** [comment]
This is because of wrong latching for which we are checking the issue

**Comment by rupalivaidya-tm** [comment]
Team is checking this issue.

**Comment by rohitgupta-tm** [comment]
This issue is because of the old entry present in W1.
All the ticket number with IP is shared with the user for review
