### ISSUE TITLE
Notified by User:Clear trap not available in alert center - where as devices is reachable with in same time stamp

### ISSUE THREAD

**Issue by santoshkhairnar-tm** [puneet-tm/wirelessone-support#99]
Clear trap not available in the alert center - whereas devices are reachable within same time stamp - this caused Green event not shared due to alert center issue.

**Comment by rupalivaidya-tm** [comment]
All the entry was present in W1à History Tab but there is some issue in ticket latching.
Wrong ticket was latched on wrong IP for this we are checking where is the issue.
Please search using IP Address.

**Comment by rohitgupta-tm** [comment]
RCA:This issue is because of the latching issue which is because of some old entry present in Redis.
